#pragma once

#include <parser.h>

// write binary to a given file, the binary is generated by a given instruction_t[]
void gen_from_instructions(char* file_name, instruction_t* instructions, size_t instructions_len);